### Rota para pegar os produtos
GET http://localhost:3010/produto

### fechando a requicisao

### Rota criando o produto
POST http://localhost:3010/produto
Content-Type: application/json

{
    "id": "2",
    "nome":" placa GTX 32'",
    "preco": 1300
}


### rota de atualização
PUT http://localhost:3010/produto/2
Content-Type: application/json

{
    "novoNome": "GTX 3080 16 gb",
    "novoPreco": 12000
}

###

### delete excluir protudto

DELETE http://localhost:3010/produto/2
Content-Type: application/json


###

### rota de deletar todos

DELETE http://localhost:3010/produto
Content-Type: application/json

###

### busca apos delete

GET http://localhost:3010/localhost:3010/produto
Content-Type: : application/json

###
